# Spring Boot configuration
spring:
  application:
    name: UtilityPayments
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  pattern:
    console: "%clr{%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M\\(%line\\) - %msg%n}{\u001B[1;32m}"
  level:
    org.springframework: info
    com.example.demowithtests: debug
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs.yaml
management:
  endpoints:
    web:
      exposure:
        include: "*"
